//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCar.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tOrderDetail
    {
        public int fId { get; set; }

        [DisplayName("訂單編號")]
        public string fOrderGuid { get; set; }

        [DisplayName("會員帳號")]
        public string fUserId { get; set; }

        [DisplayName("產品編號")]
        public string fPId { get; set; }

        [DisplayName("品名")]
        public string fName { get; set; }

        [DisplayName("單價")]
        public Nullable<int> fPrice { get; set; }

        [DisplayName("訂單數量")]
        public Nullable<int> fQty { get; set; }

        [DisplayName("是否為訂單")]
        public string fIsApproved { get; set; }
    }
}
