//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCar.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tProduct
    {
        public int fId { get; set; }
        [DisplayName("產品編號")]
        public string fPId { get; set; }

        [DisplayName("品名")]
        public string fName { get; set; }

        [DisplayName("單價")]
        public Nullable<int> fPrice { get; set; }

        [DisplayName("圖示")]
        public string fImg { get; set; }
    }
}
